### ISSUE TITLE
Demo site requires manual opt in of site apps

### ISSUE THREAD

**Issue by banagale** [PostHog/sidecar#3]
It seems like http://sidecar-panel.vercel.app/ is intended to present an example SaaS that I might want to view user data from.

I provided my initial details which seemed to be accepted.

However, further use failed and I noticed following error in my console:

>"PostHog site apps are disabled. Enable the "opt_in_site_apps" config to proceed." 

I found [this post](https://github.com/PostHog/meta/issues/63#issuecomment-1273396426) which offered the following for handling this:

```
posthog.init("api_key", { 
    "api_host": "https://app.posthog.com/",
    "opt_in_site_apps": true 
})
```

I went ahead and ran that in console and was able to get what I believe is expected behavior out of the site.  This is a cool idea and has made me think about how my employer could present data to customers in other applications.

Anyhow, it may be helpful to mention this step in the readme. I also found I did not need to restart my system, though I did restart chrome just in case.

Initially, I tried just loading up Sentry.io, thinking that would be a relevant SaaS to bring PH user data into.  But it was unclear how to make the extension do its thing, or if there was some config I needed to do.

**Comment by pjhul** [comment]
Hey @banagale, thanks for giving this a try! 

Excited to hear your interest in this project 🙌 

Apologies, I totally misread your report! I've added the `opt_in_site_apps` option and will open a PR soon, thanks!

~~I'm curious to hear more about the error you saw, since you shouldn't need to enable site apps to get this working. Did you see this message before or after you configured your settings?~~

**Comment by pjhul** [comment]
Just added this setting, thanks again for your report!

**Comment by banagale** [comment]
Super glad it was helpful. This is an inspiring concept.
